In [1]:
import pandas as pd

In [ ]:
#Create a DataFrame

In [2]:
data = {
    "Name": ["Rahul", "Priya", "Arjun"],
    "Age": [23, 25, 22],
    "City": ["Hyderabad", "Bengaluru", "Chennai"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age       City
0  Rahul   23  Hyderabad
1  Priya   25  Bengaluru
2  Arjun   22    Chennai

In [3]:
data = [
    {"Name": "Rahul", "Age": 23},
    {"Name": "Priya", "Age": 25},
    {"Name": "Arjun", "Age": 22}
]

df = pd.DataFrame(data)

print(df)

    Name  Age
0  Rahul   23
1  Priya   25
2  Arjun   22

In [6]:
df = pd.read_csv("Ecommerce_Sales_Dataset.csv")

In [7]:
print(df)

    Order_ID  Order_Date Customer_Name        City           State  \
0    ORD0001  2025-04-25        Bhavya  Vijayawada  Andhra Pradesh
1    ORD0002  2025-01-16        Ananya       Kochi          Kerala
2    ORD0003  2025-11-29          Riya      Jaipur       Rajasthan
3    ORD0004  2025-03-23        Nikhil      Jaipur       Rajasthan
4    ORD0005  2025-02-19         Manoj     Chennai      Tamil Nadu
..       ...         ...           ...         ...             ...
995  ORD0996  2025-03-19          Riya   Bengaluru       Karnataka
996  ORD0997  2025-01-19         Rahul     Chennai      Tamil Nadu
997  ORD0998  2025-09-11        Aditya     Kolkata     West Bengal
998  ORD0999  2025-03-17         Arjun       Kochi          Kerala
999  ORD1000  2025-09-18        Harsha      Mumbai     Maharashtra

          Product         Category  Quantity  Unit_Price  Discount_Percent  \
0        Backpack      Accessories         1     1719.01                15
1        Backpack      Accessories         1     1771.89                10
2    Office Chair        Furniture         1     7988.02                10
3         Monitor      Electronics         3    12886.32                20
4          Tablet      Electronics         3    16533.89                 0
..            ...              ...       ...         ...               ...
995  Coffee Maker  Home Appliances         3     7142.93                15
996        Laptop      Electronics         2    42568.74                 0
997         Shoes          Fashion         4     3516.93                 0
998         Shoes          Fashion         4     3195.51                10
999    Headphones      Electronics         2     2334.15                20

     Discount_Amount   Revenue    Payment_Method Order_Status
0             257.85   1461.16               UPI     Returned
1             177.19   1594.70       Credit Card    Delivered
2             798.80   7189.22       Credit Card      Shipped
3            7731.79  30927.17        Debit Card    Delivered
4               0.00  49601.67  Cash on Delivery    Delivered
..               ...       ...               ...          ...
995          3214.32  18214.47       Net Banking     Returned
996             0.00  85137.48       Credit Card    Delivered
997             0.00  14067.72        Debit Card      Shipped
998          1278.20  11503.84               UPI    Delivered
999           933.66   3734.64  Cash on Delivery    Cancelled

[1000 rows x 14 columns]

In [8]:
df

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [9]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered

In [10]:
df.head(10)

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
5,ORD0006,2025-07-13,Ananya,Hyderabad,Telangana,Smartwatch,Electronics,4,5087.31,10,2034.92,18314.32,Debit Card,Cancelled
6,ORD0007,2025-02-05,Aditya,Jaipur,Rajasthan,Jeans,Fashion,3,1689.22,10,506.77,4560.89,Credit Card,Returned
7,ORD0008,2025-02-21,Meena,Mumbai,Maharashtra,T-Shirt,Fashion,1,851.90,20,170.38,681.52,Net Banking,Delivered
8,ORD0009,2025-12-10,Harsha,Pune,Maharashtra,Backpack,Accessories,2,1747.90,5,174.79,3321.01,UPI,Returned
9,ORD0010,2025-08-25,Meena,Bengaluru,Karnataka,Desk,Furniture,5,6642.74,15,4982.05,28231.65,Cash on Delivery,Delivered

In [11]:
df.tail()

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [12]:
df.tail(10)

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
990,ORD0991,2025-11-14,Meena,Jaipur,Rajasthan,Desk,Furniture,1,6655.12,0,0.00,6655.12,Net Banking,Delivered
991,ORD0992,2025-04-02,Harsha,Pune,Maharashtra,Backpack,Accessories,2,1634.80,10,326.96,2942.64,Cash on Delivery,Delivered
992,ORD0993,2025-12-30,Ravi,Pune,Maharashtra,Monitor,Electronics,4,11015.16,0,0.00,44060.64,Credit Card,Shipped
993,ORD0994,2025-09-13,Harsha,Vijayawada,Andhra Pradesh,Smartwatch,Electronics,3,6026.37,0,0.00,18079.11,Debit Card,Returned
994,ORD0995,2025-05-16,Ravi,Delhi,Delhi,Coffee Maker,Home Appliances,3,6646.81,5,997.02,18943.41,Net Banking,Delivered
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [13]:
df.shape

(1000, 14)

In [14]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'City', 'State', 'Product',
       'Category', 'Quantity', 'Unit_Price', 'Discount_Percent',
       'Discount_Amount', 'Revenue', 'Payment_Method', 'Order_Status'],
      dtype='str')

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   str
 1   Order_Date        1000 non-null   str
 2   Customer_Name     1000 non-null   str
 3   City              1000 non-null   str
 4   State             1000 non-null   str
 5   Product           1000 non-null   str
 6   Category          1000 non-null   str
 7   Quantity          1000 non-null   int64
 8   Unit_Price        1000 non-null   float64
 9   Discount_Percent  1000 non-null   int64
 10  Discount_Amount   1000 non-null   float64
 11  Revenue           1000 non-null   float64
 12  Payment_Method    1000 non-null   str
 13  Order_Status      1000 non-null   str
dtypes: float64(3), int64(2), str(9)
memory usage: 183.4 KB

In [17]:
df.describe()

,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.00000
mean,2.99100,9329.937630,8.965000,2544.149440,25132.89854
std,1.38883,11109.553478,6.877578,4945.036551,34553.97518
min,1.00000,815.070000,0.000000,0.000000,681.52000
25%,2.00000,2166.470000,0.000000,0.000000,5216.51000
50%,3.00000,5328.430000,10.000000,830.215000,12448.19500
75%,4.00000,11467.122500,15.000000,2595.282500,28923.91500
max,5.00000,49371.880000,20.000000,49308.270000,246859.40000

In [18]:
df["Product"]

0          Backpack
1          Backpack
2      Office Chair
3           Monitor
4            Tablet
           ...
995    Coffee Maker
996          Laptop
997           Shoes
998           Shoes
999      Headphones
Name: Product, Length: 1000, dtype: str

In [19]:
df[["Product", "Revenue"]]

          Product   Revenue
0        Backpack   1461.16
1        Backpack   1594.70
2    Office Chair   7189.22
3         Monitor  30927.17
4          Tablet  49601.67
..            ...       ...
995  Coffee Maker  18214.47
996        Laptop  85137.48
997         Shoes  14067.72
998         Shoes  11503.84
999    Headphones   3734.64

[1000 rows x 2 columns]

In [20]:
df[["Product", "Category", "Revenue"]]

          Product         Category   Revenue
0        Backpack      Accessories   1461.16
1        Backpack      Accessories   1594.70
2    Office Chair        Furniture   7189.22
3         Monitor      Electronics  30927.17
4          Tablet      Electronics  49601.67
..            ...              ...       ...
995  Coffee Maker  Home Appliances  18214.47
996        Laptop      Electronics  85137.48
997         Shoes          Fashion  14067.72
998         Shoes          Fashion  11503.84
999    Headphones      Electronics   3734.64

[1000 rows x 3 columns]

In [21]:
df.iloc[0]

Order_ID                   ORD0001
Order_Date              2025-04-25
Customer_Name               Bhavya
City                    Vijayawada
State               Andhra Pradesh
Product                   Backpack
Category               Accessories
Quantity                         1
Unit_Price                 1719.01
Discount_Percent                15
Discount_Amount             257.85
Revenue                    1461.16
Payment_Method                 UPI
Order_Status              Returned
Name: 0, dtype: object

In [22]:
df.iloc[0:5]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered

In [23]:
df.iloc[10]

Order_ID                ORD0011
Order_Date           2025-06-11
Customer_Name             Meena
City                       Pune
State               Maharashtra
Product              Headphones
Category            Electronics
Quantity                      1
Unit_Price               2660.9
Discount_Percent              0
Discount_Amount             0.0
Revenue                  2660.9
Payment_Method              UPI
Order_Status          Delivered
Name: 10, dtype: object

In [24]:
df.iloc[10:21]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
10,ORD0011,2025-06-11,Meena,Pune,Maharashtra,Headphones,Electronics,1,2660.90,0,0.00,2660.90,UPI,Delivered
11,ORD0012,2025-07-22,Varun,Jaipur,Rajasthan,Headphones,Electronics,3,2577.72,0,0.00,7733.16,Credit Card,Shipped
12,ORD0013,2025-05-15,Sanjay,Bengaluru,Karnataka,Smartwatch,Electronics,2,5567.50,15,1670.25,9464.75,Cash on Delivery,Shipped
13,ORD0014,2025-02-16,Aditya,Pune,Maharashtra,Gaming Mouse,Gaming,2,2204.19,0,0.00,4408.38,Credit Card,Delivered
14,ORD0015,2025-07-15,Sneha,Bengaluru,Karnataka,Backpack,Accessories,4,1642.87,10,657.15,5914.33,Cash on Delivery,Shipped
15,ORD0016,2025-12-16,Riya,Kochi,Kerala,Smartwatch,Electronics,1,5742.79,15,861.42,4881.37,Debit Card,Delivered
16,ORD0017,2025-05-15,Ravi,Mumbai,Maharashtra,Smartphone,Electronics,4,21796.38,0,0.00,87185.52,Cash on Delivery,Delivered
17,ORD0018,2025-11-08,Deepak,Vijayawada,Andhra Pradesh,Coffee Maker,Home Appliances,3,6680.63,20,4008.38,16033.51,Debit Card,Delivered
18,ORD0019,2025-01-01,Sneha,Bengaluru,Karnataka,T-Shirt,Fashion,5,976.04,20,976.04,3904.16,Net Banking,Delivered
19,ORD0020,2025-05-03,Aditya,Vijayawada,Andhra Pradesh,Laptop,Electronics,3,47760.97,20,28656.58,114626.33,Cash on Delivery,Delivered
20,ORD0021,2025-09-30,Bhavya,Vijayawada,Andhra Pradesh,Smartphone,Electronics,4,20104.54,20,16083.63,64334.53,Net Banking,Delivered

In [25]:
df[df["Revenue"] > 10000]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
5,ORD0006,2025-07-13,Ananya,Hyderabad,Telangana,Smartwatch,Electronics,4,5087.31,10,2034.92,18314.32,Debit Card,Cancelled
9,ORD0010,2025-08-25,Meena,Bengaluru,Karnataka,Desk,Furniture,5,6642.74,15,4982.05,28231.65,Cash on Delivery,Delivered
16,ORD0017,2025-05-15,Ravi,Mumbai,Maharashtra,Smartphone,Electronics,4,21796.38,0,0.00,87185.52,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,ORD0995,2025-05-16,Ravi,Delhi,Delhi,Coffee Maker,Home Appliances,3,6646.81,5,997.02,18943.41,Net Banking,Delivered
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered

In [26]:
df[df["Quantity"] > 3]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
5,ORD0006,2025-07-13,Ananya,Hyderabad,Telangana,Smartwatch,Electronics,4,5087.31,10,2034.92,18314.32,Debit Card,Cancelled
9,ORD0010,2025-08-25,Meena,Bengaluru,Karnataka,Desk,Furniture,5,6642.74,15,4982.05,28231.65,Cash on Delivery,Delivered
14,ORD0015,2025-07-15,Sneha,Bengaluru,Karnataka,Backpack,Accessories,4,1642.87,10,657.15,5914.33,Cash on Delivery,Shipped
16,ORD0017,2025-05-15,Ravi,Mumbai,Maharashtra,Smartphone,Electronics,4,21796.38,0,0.00,87185.52,Cash on Delivery,Delivered
18,ORD0019,2025-01-01,Sneha,Bengaluru,Karnataka,T-Shirt,Fashion,5,976.04,20,976.04,3904.16,Net Banking,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
986,ORD0987,2025-05-29,Harsha,Bengaluru,Karnataka,Gaming Mouse,Gaming,4,2044.21,20,1635.37,6541.47,Cash on Delivery,Delivered
988,ORD0989,2025-07-16,Nikhil,Pune,Maharashtra,Tablet,Electronics,4,16963.98,15,10178.39,57677.53,Cash on Delivery,Returned
992,ORD0993,2025-12-30,Ravi,Pune,Maharashtra,Monitor,Electronics,4,11015.16,0,0.00,44060.64,Credit Card,Shipped
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered

In [27]:
df[df["Category"] == "Electronics"]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
5,ORD0006,2025-07-13,Ananya,Hyderabad,Telangana,Smartwatch,Electronics,4,5087.31,10,2034.92,18314.32,Debit Card,Cancelled
10,ORD0011,2025-06-11,Meena,Pune,Maharashtra,Headphones,Electronics,1,2660.90,0,0.00,2660.90,UPI,Delivered
11,ORD0012,2025-07-22,Varun,Jaipur,Rajasthan,Headphones,Electronics,3,2577.72,0,0.00,7733.16,Credit Card,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,ORD0990,2025-06-20,Divya,Vijayawada,Andhra Pradesh,Smartwatch,Electronics,1,5014.63,10,501.46,4513.17,Debit Card,Shipped
992,ORD0993,2025-12-30,Ravi,Pune,Maharashtra,Monitor,Electronics,4,11015.16,0,0.00,44060.64,Credit Card,Shipped
993,ORD0994,2025-09-13,Harsha,Vijayawada,Andhra Pradesh,Smartwatch,Electronics,3,6026.37,0,0.00,18079.11,Debit Card,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [28]:
df[df["City"] == "Hyderabad"]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
5,ORD0006,2025-07-13,Ananya,Hyderabad,Telangana,Smartwatch,Electronics,4,5087.31,10,2034.92,18314.32,Debit Card,Cancelled
51,ORD0052,2025-02-05,Harsha,Hyderabad,Telangana,Headphones,Electronics,2,2414.13,10,482.83,4345.43,Cash on Delivery,Delivered
71,ORD0072,2025-08-03,Riya,Hyderabad,Telangana,Monitor,Electronics,3,12608.34,5,1891.25,35933.77,Cash on Delivery,Returned
87,ORD0088,2025-09-07,Deepak,Hyderabad,Telangana,Gaming Keyboard,Gaming,4,4342.51,20,3474.01,13896.03,Debit Card,Delivered
90,ORD0091,2025-12-21,Divya,Hyderabad,Telangana,Monitor,Electronics,1,11331.83,5,566.59,10765.24,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
942,ORD0943,2025-07-13,Sneha,Hyderabad,Telangana,Office Chair,Furniture,4,8490.97,5,1698.19,32265.69,Debit Card,Returned
947,ORD0948,2025-10-18,Ravi,Hyderabad,Telangana,Gaming Keyboard,Gaming,4,4827.03,15,2896.22,16411.90,Debit Card,Shipped
962,ORD0963,2025-02-12,Kiran,Hyderabad,Telangana,Backpack,Accessories,4,1627.17,20,1301.74,5206.94,Debit Card,Cancelled
970,ORD0971,2025-06-08,Varun,Hyderabad,Telangana,Laptop,Electronics,2,45474.55,5,4547.45,86401.65,Debit Card,Returned
976,ORD0977,2025-11-19,Pooja,Hyderabad,Telangana,Monitor,Electronics,1,12339.82,15,1850.97,10488.85,Credit Card,Returned

In [29]:
df[(df["Category"] == "Electronics") & (df["Revenue"] > 20000)]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
16,ORD0017,2025-05-15,Ravi,Mumbai,Maharashtra,Smartphone,Electronics,4,21796.38,0,0.00,87185.52,Cash on Delivery,Delivered
19,ORD0020,2025-05-03,Aditya,Vijayawada,Andhra Pradesh,Laptop,Electronics,3,47760.97,20,28656.58,114626.33,Cash on Delivery,Delivered
20,ORD0021,2025-09-30,Bhavya,Vijayawada,Andhra Pradesh,Smartphone,Electronics,4,20104.54,20,16083.63,64334.53,Net Banking,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,ORD0985,2025-05-17,Kavya,Chennai,Tamil Nadu,Smartphone,Electronics,2,23962.63,0,0.00,47925.26,Net Banking,Returned
987,ORD0988,2025-08-23,Ananya,Chennai,Tamil Nadu,Monitor,Electronics,3,12442.24,10,3732.67,33594.05,Net Banking,Delivered
988,ORD0989,2025-07-16,Nikhil,Pune,Maharashtra,Tablet,Electronics,4,16963.98,15,10178.39,57677.53,Cash on Delivery,Returned
992,ORD0993,2025-12-30,Ravi,Pune,Maharashtra,Monitor,Electronics,4,11015.16,0,0.00,44060.64,Credit Card,Shipped
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered

In [30]:
df[(df["Category"] == "Electronics") | (df["Category"] == "Gaming")]

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
5,ORD0006,2025-07-13,Ananya,Hyderabad,Telangana,Smartwatch,Electronics,4,5087.31,10,2034.92,18314.32,Debit Card,Cancelled
10,ORD0011,2025-06-11,Meena,Pune,Maharashtra,Headphones,Electronics,1,2660.90,0,0.00,2660.90,UPI,Delivered
11,ORD0012,2025-07-22,Varun,Jaipur,Rajasthan,Headphones,Electronics,3,2577.72,0,0.00,7733.16,Credit Card,Shipped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,ORD0990,2025-06-20,Divya,Vijayawada,Andhra Pradesh,Smartwatch,Electronics,1,5014.63,10,501.46,4513.17,Debit Card,Shipped
992,ORD0993,2025-12-30,Ravi,Pune,Maharashtra,Monitor,Electronics,4,11015.16,0,0.00,44060.64,Credit Card,Shipped
993,ORD0994,2025-09-13,Harsha,Vijayawada,Andhra Pradesh,Smartwatch,Electronics,3,6026.37,0,0.00,18079.11,Debit Card,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [31]:
df.sort_values("Revenue")

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
7,ORD0008,2025-02-21,Meena,Mumbai,Maharashtra,T-Shirt,Fashion,1,851.90,20,170.38,681.52,Net Banking,Delivered
461,ORD0462,2025-10-05,Nikhil,Vijayawada,Andhra Pradesh,T-Shirt,Fashion,1,871.88,15,130.78,741.10,Credit Card,Cancelled
829,ORD0830,2025-11-24,Aarav,Kolkata,West Bengal,T-Shirt,Fashion,1,836.79,10,83.68,753.11,Net Banking,Delivered
919,ORD0920,2025-04-13,Charan,Vijayawada,Andhra Pradesh,T-Shirt,Fashion,1,846.97,10,84.70,762.27,Debit Card,Returned
944,ORD0945,2025-06-24,Meena,Jaipur,Rajasthan,T-Shirt,Fashion,1,970.44,20,194.09,776.35,Net Banking,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
615,ORD0616,2025-11-11,Charan,Jaipur,Rajasthan,Laptop,Electronics,5,46786.05,10,23393.03,210537.22,UPI,Returned
428,ORD0429,2025-07-22,Rahul,Bengaluru,Karnataka,Laptop,Electronics,5,47895.17,10,23947.58,215528.27,Net Banking,Delivered
33,ORD0034,2025-01-30,Aditya,Jaipur,Rajasthan,Laptop,Electronics,5,47231.78,0,0.00,236158.90,Net Banking,Cancelled
440,ORD0441,2025-06-24,Charan,Pune,Maharashtra,Laptop,Electronics,5,47758.01,0,0.00,238790.05,UPI,Delivered
948,ORD0949,2025-07-13,Sanjay,Kolkata,West Bengal,Laptop,Electronics,5,49371.88,0,0.00,246859.40,Debit Card,Shipped

In [32]:
df.sort_values("Revenue", ascending=False)

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
948,ORD0949,2025-07-13,Sanjay,Kolkata,West Bengal,Laptop,Electronics,5,49371.88,0,0.00,246859.40,Debit Card,Shipped
440,ORD0441,2025-06-24,Charan,Pune,Maharashtra,Laptop,Electronics,5,47758.01,0,0.00,238790.05,UPI,Delivered
33,ORD0034,2025-01-30,Aditya,Jaipur,Rajasthan,Laptop,Electronics,5,47231.78,0,0.00,236158.90,Net Banking,Cancelled
428,ORD0429,2025-07-22,Rahul,Bengaluru,Karnataka,Laptop,Electronics,5,47895.17,10,23947.58,215528.27,Net Banking,Delivered
615,ORD0616,2025-11-11,Charan,Jaipur,Rajasthan,Laptop,Electronics,5,46786.05,10,23393.03,210537.22,UPI,Returned
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
944,ORD0945,2025-06-24,Meena,Jaipur,Rajasthan,T-Shirt,Fashion,1,970.44,20,194.09,776.35,Net Banking,Delivered
919,ORD0920,2025-04-13,Charan,Vijayawada,Andhra Pradesh,T-Shirt,Fashion,1,846.97,10,84.70,762.27,Debit Card,Returned
829,ORD0830,2025-11-24,Aarav,Kolkata,West Bengal,T-Shirt,Fashion,1,836.79,10,83.68,753.11,Net Banking,Delivered
461,ORD0462,2025-10-05,Nikhil,Vijayawada,Andhra Pradesh,T-Shirt,Fashion,1,871.88,15,130.78,741.10,Credit Card,Cancelled
7,ORD0008,2025-02-21,Meena,Mumbai,Maharashtra,T-Shirt,Fashion,1,851.90,20,170.38,681.52,Net Banking,Delivered

In [33]:
df.sort_values("Revenue", ascending=False).head(10)

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
948,ORD0949,2025-07-13,Sanjay,Kolkata,West Bengal,Laptop,Electronics,5,49371.88,0,0.00,246859.40,Debit Card,Shipped
440,ORD0441,2025-06-24,Charan,Pune,Maharashtra,Laptop,Electronics,5,47758.01,0,0.00,238790.05,UPI,Delivered
33,ORD0034,2025-01-30,Aditya,Jaipur,Rajasthan,Laptop,Electronics,5,47231.78,0,0.00,236158.90,Net Banking,Cancelled
428,ORD0429,2025-07-22,Rahul,Bengaluru,Karnataka,Laptop,Electronics,5,47895.17,10,23947.58,215528.27,Net Banking,Delivered
615,ORD0616,2025-11-11,Charan,Jaipur,Rajasthan,Laptop,Electronics,5,46786.05,10,23393.03,210537.22,UPI,Returned
441,ORD0442,2025-02-26,Ravi,Bengaluru,Karnataka,Laptop,Electronics,5,48755.02,15,36566.26,207208.84,UPI,Delivered
227,ORD0228,2025-01-18,Bhavya,Bengaluru,Karnataka,Laptop,Electronics,5,47531.81,15,35648.86,202010.19,Credit Card,Delivered
318,ORD0319,2025-11-13,Varun,Chennai,Tamil Nadu,Laptop,Electronics,5,43858.81,10,21929.40,197364.65,Cash on Delivery,Returned
794,ORD0795,2025-02-26,Kavya,Hyderabad,Telangana,Laptop,Electronics,5,49308.27,20,49308.27,197233.08,Credit Card,Delivered
235,ORD0236,2025-10-10,Bhavya,Pune,Maharashtra,Laptop,Electronics,5,43820.20,10,21910.10,197190.90,UPI,Cancelled

In [34]:
df.sort_values("Quantity", ascending=False)

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
971,ORD0972,2025-08-15,Meena,Vijayawada,Andhra Pradesh,Coffee Maker,Home Appliances,5,6157.30,20,6157.30,24629.20,Net Banking,Delivered
964,ORD0965,2025-03-03,Ravi,Vijayawada,Andhra Pradesh,Headphones,Electronics,5,2500.12,15,1875.09,10625.51,Cash on Delivery,Returned
728,ORD0729,2025-11-02,Divya,Mumbai,Maharashtra,Desk,Furniture,5,7157.31,10,3578.66,32207.89,UPI,Delivered
723,ORD0724,2025-03-12,Sanjay,Kolkata,West Bengal,Gaming Keyboard,Gaming,5,4236.08,0,0.00,21180.40,Credit Card,Cancelled
392,ORD0393,2025-08-08,Kiran,Vijayawada,Andhra Pradesh,Tablet,Electronics,5,17582.51,15,13186.88,74725.67,Credit Card,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,ORD0599,2025-09-16,Vishnu,Vijayawada,Andhra Pradesh,Tablet,Electronics,1,18081.76,0,0.00,18081.76,Credit Card,Shipped
10,ORD0011,2025-06-11,Meena,Pune,Maharashtra,Headphones,Electronics,1,2660.90,0,0.00,2660.90,UPI,Delivered
593,ORD0594,2025-03-24,Bhavya,Chennai,Tamil Nadu,Laptop,Electronics,1,45661.38,0,0.00,45661.38,Cash on Delivery,Returned
7,ORD0008,2025-02-21,Meena,Mumbai,Maharashtra,T-Shirt,Fashion,1,851.90,20,170.38,681.52,Net Banking,Delivered
586,ORD0587,2025-12-27,Ravi,Hyderabad,Telangana,Coffee Maker,Home Appliances,1,6271.29,15,940.69,5330.60,Debit Card,Returned

In [36]:
df["Gross_Sales"] = df["Unit_Price"] * df["Quantity"]

In [37]:
df["Gross_Sales"]

0       1719.01
1       1771.89
2       7988.02
3      38658.96
4      49601.67
         ...
995    21428.79
996    85137.48
997    14067.72
998    12782.04
999     4668.30
Name: Gross_Sales, Length: 1000, dtype: float64

In [38]:
df["Final_Revenue"] = df["Gross_Sales"] - df["Discount_Amount"]

In [39]:
df["Final_Revenue"]

0       1461.16
1       1594.70
2       7189.22
3      30927.17
4      49601.67
         ...
995    18214.47
996    85137.48
997    14067.72
998    11503.84
999     3734.64
Name: Final_Revenue, Length: 1000, dtype: float64

In [40]:
df["Unit_Price"] = df["Unit_Price"] * 1.10

In [41]:
df["Unit_Price"]

0       1890.911
1       1949.079
2       8786.822
3      14174.952
4      18187.279
         ...
995     7857.223
996    46825.614
997     3868.623
998     3515.061
999     2567.565
Name: Unit_Price, Length: 1000, dtype: float64

In [42]:
df["Product"] = df["Product"].str.upper()

In [43]:
df["Product"]

0          BACKPACK
1          BACKPACK
2      OFFICE CHAIR
3           MONITOR
4            TABLET
           ...
995    COFFEE MAKER
996          LAPTOP
997           SHOES
998           SHOES
999      HEADPHONES
Name: Product, Length: 1000, dtype: str

In [44]:
df.rename(columns={"Revenue": "Total_Revenue"},inplace=True)

In [45]:
df["Total_Revenue"]

0       1461.16
1       1594.70
2       7189.22
3      30927.17
4      49601.67
         ...
995    18214.47
996    85137.48
997    14067.72
998    11503.84
999     3734.64
Name: Total_Revenue, Length: 1000, dtype: float64

In [46]:
df.rename(columns={"Customer_Name": "Customer","Unit_Price": "Price","Revenue": "Total_Revenue"},inplace=True)

In [54]:
df[["Customer","Price","Total_Revenue"]]

    Customer      Price  Total_Revenue
0     Bhavya   1890.911        1461.16
1     Ananya   1949.079        1594.70
2       Riya   8786.822        7189.22
3     Nikhil  14174.952       30927.17
4      Manoj  18187.279       49601.67
..       ...        ...            ...
995     Riya   7857.223       18214.47
996    Rahul  46825.614       85137.48
997   Aditya   3868.623       14067.72
998    Arjun   3515.061       11503.84
999   Harsha   2567.565        3734.64

[1000 rows x 3 columns]

In [55]:
df.drop("Discount_Percent", axis=1, inplace=True)

In [56]:
df

,Order_ID,Order_Date,Customer,City,State,Product,Category,Quantity,Price,Discount_Amount,Total_Revenue,Payment_Method,Order_Status,Gross_Sales,Final_Revenue
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,BACKPACK,Accessories,1,1890.911,257.85,1461.16,UPI,Returned,1719.01,1461.16
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,BACKPACK,Accessories,1,1949.079,177.19,1594.70,Credit Card,Delivered,1771.89,1594.70
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,OFFICE CHAIR,Furniture,1,8786.822,798.80,7189.22,Credit Card,Shipped,7988.02,7189.22
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,MONITOR,Electronics,3,14174.952,7731.79,30927.17,Debit Card,Delivered,38658.96,30927.17
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,TABLET,Electronics,3,18187.279,0.00,49601.67,Cash on Delivery,Delivered,49601.67,49601.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,COFFEE MAKER,Home Appliances,3,7857.223,3214.32,18214.47,Net Banking,Returned,21428.79,18214.47
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,LAPTOP,Electronics,2,46825.614,0.00,85137.48,Credit Card,Delivered,85137.48,85137.48
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,SHOES,Fashion,4,3868.623,0.00,14067.72,Debit Card,Shipped,14067.72,14067.72
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,SHOES,Fashion,4,3515.061,1278.20,11503.84,UPI,Delivered,12782.04,11503.84
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,HEADPHONES,Electronics,2,2567.565,933.66,3734.64,Cash on Delivery,Cancelled,4668.30,3734.64

In [58]:
df.drop("Payment_Method",axis=1,inplace=True)

In [59]:
df

,Order_ID,Order_Date,Customer,City,State,Product,Category,Quantity,Price,Discount_Amount,Total_Revenue,Order_Status,Gross_Sales,Final_Revenue
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,BACKPACK,Accessories,1,1890.911,257.85,1461.16,Returned,1719.01,1461.16
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,BACKPACK,Accessories,1,1949.079,177.19,1594.70,Delivered,1771.89,1594.70
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,OFFICE CHAIR,Furniture,1,8786.822,798.80,7189.22,Shipped,7988.02,7189.22
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,MONITOR,Electronics,3,14174.952,7731.79,30927.17,Delivered,38658.96,30927.17
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,TABLET,Electronics,3,18187.279,0.00,49601.67,Delivered,49601.67,49601.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,COFFEE MAKER,Home Appliances,3,7857.223,3214.32,18214.47,Returned,21428.79,18214.47
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,LAPTOP,Electronics,2,46825.614,0.00,85137.48,Delivered,85137.48,85137.48
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,SHOES,Fashion,4,3868.623,0.00,14067.72,Shipped,14067.72,14067.72
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,SHOES,Fashion,4,3515.061,1278.20,11503.84,Delivered,12782.04,11503.84
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,HEADPHONES,Electronics,2,2567.565,933.66,3734.64,Cancelled,4668.30,3734.64

In [61]:
df.groupby("Category")["Total_Revenue"].sum()

Category
Accessories          271383.73
Electronics        18428388.98
Fashion             1066316.06
Furniture           3057726.85
Gaming              1360399.12
Home Appliances      948683.80
Name: Total_Revenue, dtype: float64

In [63]:
df.groupby("City")["Total_Revenue"].sum()

City
Bengaluru     2844519.73
Chennai       2123338.79
Delhi         2366584.81
Hyderabad     2189305.51
Jaipur        2501060.59
Kochi         2551141.58
Kolkata       2114586.38
Mumbai        2958166.56
Pune          2077983.36
Vijayawada    3406211.23
Name: Total_Revenue, dtype: float64

In [65]:
df["Total_Revenue"].sum()

np.float64(25132898.54)

In [66]:
df["Quantity"].sum()

np.int64(2991)

In [67]:
df["Total_Revenue"].mean()

np.float64(25132.89854)

In [68]:
df["Quantity"].mean()

np.float64(2.991)

In [70]:
df["Price"].mean()

np.float64(10262.931392999999)

In [71]:
df["Order_ID"].count()

np.int64(1000)

In [ ]:
df["Order_ID"].count()

In [72]:
df["Category"].count()

np.int64(1000)

In [73]:
df.groupby("Category")["Order_ID"].count()

Category
Accessories         67
Electronics        393
Fashion            214
Furniture          135
Gaming             137
Home Appliances     54
Name: Order_ID, dtype: int64

In [74]:
df["Total_Revenue"].max()

np.float64(246859.4)

In [75]:
df["Price"].max()

np.float64(54309.068)

In [76]:
df["Total_Revenue"].agg(["sum", "mean", "count", "min", "max"])

sum      2.513290e+07
mean     2.513290e+04
count    1.000000e+03
min      6.815200e+02
max      2.468594e+05
Name: Total_Revenue, dtype: float64

In [77]:
df.groupby("Category")["Total_Revenue"].agg(["sum", "mean", "count", "min", "max"])

                         sum          mean  count      min        max
Category
Accessories        271383.73   4050.503433     67  1461.16    8616.25
Electronics      18428388.98  46891.575013    393  1959.19  246859.40
Fashion           1066316.06   4982.785327    214   681.52   15525.95
Furniture         3057726.85  22649.828519    135  5381.50   43876.40
Gaming            1360399.12   9929.920584    137  1704.17   24536.60
Home Appliances    948683.80  17568.218519     54  5330.60   32203.55

In [78]:
df.to_csv("processed_ecommerce_sales.csv", index=False)

In [79]:
df

,Order_ID,Order_Date,Customer,City,State,Product,Category,Quantity,Price,Discount_Amount,Total_Revenue,Order_Status,Gross_Sales,Final_Revenue
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,BACKPACK,Accessories,1,1890.911,257.85,1461.16,Returned,1719.01,1461.16
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,BACKPACK,Accessories,1,1949.079,177.19,1594.70,Delivered,1771.89,1594.70
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,OFFICE CHAIR,Furniture,1,8786.822,798.80,7189.22,Shipped,7988.02,7189.22
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,MONITOR,Electronics,3,14174.952,7731.79,30927.17,Delivered,38658.96,30927.17
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,TABLET,Electronics,3,18187.279,0.00,49601.67,Delivered,49601.67,49601.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,COFFEE MAKER,Home Appliances,3,7857.223,3214.32,18214.47,Returned,21428.79,18214.47
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,LAPTOP,Electronics,2,46825.614,0.00,85137.48,Delivered,85137.48,85137.48
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,SHOES,Fashion,4,3868.623,0.00,14067.72,Shipped,14067.72,14067.72
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,SHOES,Fashion,4,3515.061,1278.20,11503.84,Delivered,12782.04,11503.84
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,HEADPHONES,Electronics,2,2567.565,933.66,3734.64,Cancelled,4668.30,3734.64