In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv("Ecommerce_Sales_Dataset.csv")

In [16]:
df

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [17]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 1000
Columns: 14

In [18]:
df.shape

(1000, 14)

In [19]:
df.columns

Index(['Order_ID', 'Order_Date', 'Customer_Name', 'City', 'State', 'Product',
       'Category', 'Quantity', 'Unit_Price', 'Discount_Percent',
       'Discount_Amount', 'Revenue', 'Payment_Method', 'Order_Status'],
      dtype='str')

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          1000 non-null   str
 1   Order_Date        1000 non-null   str
 2   Customer_Name     1000 non-null   str
 3   City              1000 non-null   str
 4   State             1000 non-null   str
 5   Product           1000 non-null   str
 6   Category          1000 non-null   str
 7   Quantity          1000 non-null   int64
 8   Unit_Price        1000 non-null   float64
 9   Discount_Percent  1000 non-null   int64
 10  Discount_Amount   1000 non-null   float64
 11  Revenue           1000 non-null   float64
 12  Payment_Method    1000 non-null   str
 13  Order_Status      1000 non-null   str
dtypes: float64(3), int64(2), str(9)
memory usage: 183.4 KB

In [21]:
df.describe()

,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue
count,1000.00000,1000.000000,1000.000000,1000.000000,1000.00000
mean,2.99100,9329.937630,8.965000,2544.149440,25132.89854
std,1.38883,11109.553478,6.877578,4945.036551,34553.97518
min,1.00000,815.070000,0.000000,0.000000,681.52000
25%,2.00000,2166.470000,0.000000,0.000000,5216.51000
50%,3.00000,5328.430000,10.000000,830.215000,12448.19500
75%,4.00000,11467.122500,15.000000,2595.282500,28923.91500
max,5.00000,49371.880000,20.000000,49308.270000,246859.40000

In [22]:
df.head()

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered

In [23]:
df.tail()

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled

In [25]:
df.isnull().sum()

Order_ID            0
Order_Date          0
Customer_Name       0
City                0
State               0
Product             0
Category            0
Quantity            0
Unit_Price          0
Discount_Percent    0
Discount_Amount     0
Revenue             0
Payment_Method      0
Order_Status        0
dtype: int64

In [26]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

Order_ID            0.0
Order_Date          0.0
Customer_Name       0.0
City                0.0
State               0.0
Product             0.0
Category            0.0
Quantity            0.0
Unit_Price          0.0
Discount_Percent    0.0
Discount_Amount     0.0
Revenue             0.0
Payment_Method      0.0
Order_Status        0.0
dtype: float64

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
df[df.duplicated()]

Empty DataFrame
Columns: [Order_ID, Order_Date, Customer_Name, City, State, Product, Category, Quantity, Unit_Price, Discount_Percent, Discount_Amount, Revenue, Payment_Method, Order_Status]
Index: []

In [30]:
df.dtypes

Order_ID                str
Order_Date              str
Customer_Name           str
City                    str
State                   str
Product                 str
Category                str
Quantity              int64
Unit_Price          float64
Discount_Percent      int64
Discount_Amount     float64
Revenue             float64
Payment_Method          str
Order_Status            str
dtype: object

In [31]:
df_dropna = df.dropna()

print("Original rows:", len(df))
print("Rows after dropna:", len(df_dropna))

Original rows: 1000
Rows after dropna: 1000

In [32]:
print("Duplicates before:", df.duplicated().sum())

df = df.drop_duplicates()

print("Duplicates after:", df.duplicated().sum())

Duplicates before: 0
Duplicates after: 0

In [33]:
df["Order_Date"] = pd.to_datetime(df["Order_Date"], errors="coerce")

In [38]:
df["Order_Date"].dtype

dtype('<M8[us]')

In [39]:
df["Year"] = df["Order_Date"].dt.year

In [40]:
df["Year"]

0      2025
1      2025
2      2025
3      2025
4      2025
       ...
995    2025
996    2025
997    2025
998    2025
999    2025
Name: Year, Length: 1000, dtype: int32

In [41]:
df["Month"] = df["Order_Date"].dt.month

In [42]:
df["Month"]

0       4
1       1
2      11
3       3
4       2
       ..
995     3
996     1
997     9
998     3
999     9
Name: Month, Length: 1000, dtype: int32

In [43]:
df["Date"] = df["Order_Date"].dt.date

In [44]:
df["Date"]

0      2025-04-25
1      2025-01-16
2      2025-11-29
3      2025-03-23
4      2025-02-19
          ...
995    2025-03-19
996    2025-01-19
997    2025-09-11
998    2025-03-17
999    2025-09-18
Name: Date, Length: 1000, dtype: object

In [52]:
df["State"] = df["State"].str.strip().str.title()

In [54]:
df["State"]

0      Andhra Pradesh
1              Kerala
2           Rajasthan
3           Rajasthan
4          Tamil Nadu
            ...
995         Karnataka
996        Tamil Nadu
997       West Bengal
998            Kerala
999       Maharashtra
Name: State, Length: 1000, dtype: str

In [53]:
df["Category"] = df["Category"].str.strip().str.title()

In [55]:
df["Category"]

0          Accessories
1          Accessories
2            Furniture
3          Electronics
4          Electronics
            ...
995    Home Appliances
996        Electronics
997            Fashion
998            Fashion
999        Electronics
Name: Category, Length: 1000, dtype: str

In [57]:
df["State"].value_counts()

State
Maharashtra       197
Andhra Pradesh    118
Rajasthan         113
Kerala            106
West Bengal       106
Karnataka         101
Telangana          90
Delhi              87
Tamil Nadu         82
Name: count, dtype: int64

In [58]:
df["Category"].value_counts()

Category
Electronics        393
Fashion            214
Gaming             137
Furniture          135
Accessories         67
Home Appliances     54
Name: count, dtype: int64

In [59]:
df["State"].unique()

<ArrowStringArray>
['Andhra Pradesh',         'Kerala',      'Rajasthan',     'Tamil Nadu',
      'Telangana',    'Maharashtra',      'Karnataka',    'West Bengal',
          'Delhi']
Length: 9, dtype: str

In [63]:
df["State"].nunique()

9

In [60]:
df["Category"].unique()

<ArrowStringArray>
[    'Accessories',       'Furniture',     'Electronics',         'Fashion',
          'Gaming', 'Home Appliances']
Length: 6, dtype: str

In [64]:
df["Category"].nunique()

6

In [65]:
df.nunique()

Order_ID            1000
Order_Date           341
Customer_Name         22
City                  10
State                  9
Product               15
Category               6
Quantity               5
Unit_Price           999
Discount_Percent       5
Discount_Amount      735
Revenue             1000
Payment_Method         5
Order_Status           4
Year                   1
Month                 12
Date                 341
Month_Name             1
dtype: int64

In [66]:
Q1 = df["Revenue"].quantile(0.25)
Q3 = df["Revenue"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[
    (df["Revenue"] < lower_bound) |
    (df["Revenue"] > upper_bound)
]

print("Number of outliers:", len(outliers))

Number of outliers: 107

In [67]:
outliers

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status,Year,Month,Date,Month_Name
16,ORD0017,2025-05-15,Ravi,Mumbai,Maharashtra,Smartphone,Electronics,4,21796.38,0,0.00,87185.52,Cash on Delivery,Delivered,2025,5,2025-05-15,<bound method DatetimeArray.month_name of <pan...
19,ORD0020,2025-05-03,Aditya,Vijayawada,Andhra Pradesh,Laptop,Electronics,3,47760.97,20,28656.58,114626.33,Cash on Delivery,Delivered,2025,5,2025-05-03,<bound method DatetimeArray.month_name of <pan...
29,ORD0030,2025-02-08,Pooja,Mumbai,Maharashtra,Tablet,Electronics,4,19348.15,0,0.00,77392.60,UPI,Cancelled,2025,2,2025-02-08,<bound method DatetimeArray.month_name of <pan...
33,ORD0034,2025-01-30,Aditya,Jaipur,Rajasthan,Laptop,Electronics,5,47231.78,0,0.00,236158.90,Net Banking,Cancelled,2025,1,2025-01-30,<bound method DatetimeArray.month_name of <pan...
35,ORD0036,2025-10-19,Divya,Chennai,Tamil Nadu,Smartphone,Electronics,4,23943.02,0,0.00,95772.08,Cash on Delivery,Cancelled,2025,10,2025-10-19,<bound method DatetimeArray.month_name of <pan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
936,ORD0937,2025-02-09,Vishnu,Mumbai,Maharashtra,Tablet,Electronics,5,16546.80,10,8273.40,74460.60,Net Banking,Cancelled,2025,2,2025-02-09,<bound method DatetimeArray.month_name of <pan...
948,ORD0949,2025-07-13,Sanjay,Kolkata,West Bengal,Laptop,Electronics,5,49371.88,0,0.00,246859.40,Debit Card,Shipped,2025,7,2025-07-13,<bound method DatetimeArray.month_name of <pan...
970,ORD0971,2025-06-08,Varun,Hyderabad,Telangana,Laptop,Electronics,2,45474.55,5,4547.45,86401.65,Debit Card,Returned,2025,6,2025-06-08,<bound method DatetimeArray.month_name of <pan...
977,ORD0978,2025-10-22,Ananya,Delhi,Delhi,Laptop,Electronics,2,43249.93,15,12974.98,73524.88,Credit Card,Delivered,2025,10,2025-10-22,<bound method DatetimeArray.month_name of <pan...
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered,2025,1,2025-01-19,<bound method DatetimeArray.month_name of <pan...

In [ ]:
## EDA Questions

In [ ]:
#Which product generates the most revenue?

In [75]:
Product_revenue = df.groupby("Product")["Revenue"].sum()
print("Product_Name:",Product_revenue.idxmax(),",","Revenue:",Product_revenue.max())

Product_Name: Laptop , Revenue: 7230166.4

In [ ]:
#Which region performs best?

In [77]:
Best_Region = df.groupby("State")["Revenue"].sum()
print("Best_Region:",Best_Region.idxmax(),",","Revenue:",Best_Region.max())

Best_Region: Maharashtra , Revenue: 5036149.92

In [78]:
#Which month has the highest sales?

In [82]:
Monthly_Sales = df.groupby("Month")["Revenue"].sum()

print("Top_Month:",Monthly_Sales.idxmax(),",","Top_Month:",Monthly_Sales.max())

Top_Month: 11 , Top_Month: 2619428.91

In [ ]:
#What is the average order value?

In [85]:
Total_Revenue = df["Revenue"].sum()
Total_Orders = df["Order_ID"].nunique()

Average_Order_Value = Total_Revenue / Total_Orders

print("Average_Order_Value:", Average_Order_Value)

Average_Order_Value: 25132.89854

In [ ]:
#Which category has the highest quantity?

In [86]:
Highest_Category_By_Quantity = df.groupby("Category")["Quantity"].sum()
print("Highest_Category:",Highest_Category_By_Quantity.idxmax(),",","Quantity:",Highest_Category_By_Quantity.max())

Highest_Category: Electronics , Quantity: 1149

In [ ]:
#Are there unusual values or outliers?

In [87]:
Q1 = df["Revenue"].quantile(0.25)
Q3 = df["Revenue"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Revenue"] < lower) |
    (df["Revenue"] > upper)
]

print("Number of revenue outliers:", len(outliers))

Number of revenue outliers: 107

In [90]:
df.to_csv("Day_18_Cleaned_Sales_Data.csv", index=False)

In [91]:
df

,Order_ID,Order_Date,Customer_Name,City,State,Product,Category,Quantity,Unit_Price,Discount_Percent,Discount_Amount,Revenue,Payment_Method,Order_Status,Year,Month,Date,Month_Name
0,ORD0001,2025-04-25,Bhavya,Vijayawada,Andhra Pradesh,Backpack,Accessories,1,1719.01,15,257.85,1461.16,UPI,Returned,2025,4,2025-04-25,<bound method DatetimeArray.month_name of <pan...
1,ORD0002,2025-01-16,Ananya,Kochi,Kerala,Backpack,Accessories,1,1771.89,10,177.19,1594.70,Credit Card,Delivered,2025,1,2025-01-16,<bound method DatetimeArray.month_name of <pan...
2,ORD0003,2025-11-29,Riya,Jaipur,Rajasthan,Office Chair,Furniture,1,7988.02,10,798.80,7189.22,Credit Card,Shipped,2025,11,2025-11-29,<bound method DatetimeArray.month_name of <pan...
3,ORD0004,2025-03-23,Nikhil,Jaipur,Rajasthan,Monitor,Electronics,3,12886.32,20,7731.79,30927.17,Debit Card,Delivered,2025,3,2025-03-23,<bound method DatetimeArray.month_name of <pan...
4,ORD0005,2025-02-19,Manoj,Chennai,Tamil Nadu,Tablet,Electronics,3,16533.89,0,0.00,49601.67,Cash on Delivery,Delivered,2025,2,2025-02-19,<bound method DatetimeArray.month_name of <pan...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,ORD0996,2025-03-19,Riya,Bengaluru,Karnataka,Coffee Maker,Home Appliances,3,7142.93,15,3214.32,18214.47,Net Banking,Returned,2025,3,2025-03-19,<bound method DatetimeArray.month_name of <pan...
996,ORD0997,2025-01-19,Rahul,Chennai,Tamil Nadu,Laptop,Electronics,2,42568.74,0,0.00,85137.48,Credit Card,Delivered,2025,1,2025-01-19,<bound method DatetimeArray.month_name of <pan...
997,ORD0998,2025-09-11,Aditya,Kolkata,West Bengal,Shoes,Fashion,4,3516.93,0,0.00,14067.72,Debit Card,Shipped,2025,9,2025-09-11,<bound method DatetimeArray.month_name of <pan...
998,ORD0999,2025-03-17,Arjun,Kochi,Kerala,Shoes,Fashion,4,3195.51,10,1278.20,11503.84,UPI,Delivered,2025,3,2025-03-17,<bound method DatetimeArray.month_name of <pan...
999,ORD1000,2025-09-18,Harsha,Mumbai,Maharashtra,Headphones,Electronics,2,2334.15,20,933.66,3734.64,Cash on Delivery,Cancelled,2025,9,2025-09-18,<bound method DatetimeArray.month_name of <pan...